jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le code
        uses: actions/checkout@v3

      - name: Créer le fichier .env.local avec les secrets
        run: |
          echo "APP_ENV=${{ secrets.APP_ENV }}" > .env.local
          echo "APP_SECRET=${{ secrets.APP_SECRET }}" >> .env.local
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env.local
          echo "JWT_PASSPHRASE=${{ secrets.JWT_PASSPHRASE }}" >> .env.local
          echo "JWT_PUBLIC_KEY='${{ secrets.JWT_PUBLIC_KEY }}'" >> .env.local
          echo "JWT_SECRET_KEY='${{ secrets.JWT_SECRET_KEY }}'" >> .env.local
          echo "TRUSTED_PROXIES=${{ secrets.TRUSTED_PROXIES }}" >> .env.local

      - name: Save SSH Private Key to a File
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > /tmp/id_rsa
          chmod 600 /tmp/id_rsa

      - name: Copier les fichiers Symfony sur la VM
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          username: admin_mona
          key: /tmp/id_rsa   # Utilisation du fichier temporaire ici
          port: 2222
          source: .
          target: /var/www/projet-groupe.dev.local-link.mona-vanwilligen.com
          strip_components: 1

      - name: Lancer les commandes Symfony sur la VM
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: admin_mona
          key: /tmp/id_rsa   # Utilisation du fichier temporaire ici aussi
          port: 2222
          script: |
            cd /var/www/projet-groupe.dev.local-link.mona-vanwilligen.com
            composer install --no-interaction --prefer-dist --optimize-autoloader
            php bin/console doctrine:migrations:migrate --no-interaction
            php bin/console cache:clear

