name: Déploiement Symfony - LOCAL LINK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le code
        uses: actions/checkout@v3

      - name: Créer le fichier .env.local avec les secrets
        run: |
          echo "APP_ENV=prod" > .env.local
          echo "APP_DEBUG=0" >> .env.local
          echo "APP_SECRET=${{ secrets.APP_SECRET }}" >> .env.local
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env.local
          echo "JWT_PASSPHRASE=${{ secrets.JWT_PASSPHRASE }}" >> .env.local
          echo "JWT_PUBLIC_KEY='${{ secrets.JWT_PUBLIC_KEY }}'" >> .env.local
          echo "JWT_SECRET_KEY='${{ secrets.JWT_SECRET_KEY }}'" >> .env.local
          echo "CORS_ALLOW_ORIGIN='${{ secrets.CORS_ALLOW_ORIGIN }}'" >> .env.local

      - name: Copier les fichiers Symfony sur la VM
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 2222
          source: .
          target: /var/www/projet-groupe.dev.local-link.mona-vanwilligen.com
          strip_components: 1

      - name: Lancer les commandes Symfony sur la VM
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 2222
          script: |
            cd /var/www/projet-groupe.dev.local-link.mona-vanwilligen.com

            # Création et permissions
            mkdir -p var/cache var/log public/uploads
            chmod -R 775 var/ public/uploads
            chown -R www-data:www-data var/ public/uploads

            # Installer les dépendances
            composer install --no-interaction --prefer-dist --optimize-autoloader

            # Migration DB
            php bin/console doctrine:migrations:migrate --no-interaction || true
            
            # Clear cache (maintenant que les droits sont bons)
            php bin/console cache:clear || true
